/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : pmeladianos
 * Created : 11/27/2015 08:49:31
 */

package gr.aueb.dbnet.importers.tdt;

import java.io.IOException;

import org.junit.*;

import static org.junit.Assert.*;
import gr.aueb.dbnet.importers.Importer;
import gr.aueb.dbnet.importers.tdt.DocumentImporter;
import gr.aueb.dbnet.util.SystemProperties;



public class DocumentImporterTest {

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
		// TODO add setup code.
	
	}

	@Before
	public void setUp() throws Exception {
		// TODO add setup code.
		SystemProperties pr=new SystemProperties();
		pr.init();
	
	}

	/**
	 *
	 * @throws IOException 
	 * @see gr.aueb.dbnet.importers.tdt.DocumentImporter#importData()
	 */
	@Test
	public void importData() throws IOException {
		Importer documentImporter=new DocumentImporter();
		documentImporter.importData(false);
		int size = documentImporter.getData().size();
		System.out.print("test loaded:"+ size+" documents");
	}

	
}
